### ISSUE TITLE
Queries

### ISSUE THREAD

**Issue by sahin** [weeyum/newrelic_mongodb#1]
Thanks for the plugin. We need it so badly.

Do you have plans to add queries like the old new relic mongodb plugin ?

**Comment by burakkeles** [comment]
+1

**Comment by adamdilek** [comment]
+1

**Comment by burakkeles** [comment]
+1

**Comment by duygupeker** [comment]
+1

**Comment by isair** [comment]
+1

**Comment by weeyum** [comment]
@sahin I'm not too familiar with the old newrelic mongodb plugin, can u be more specific about what you are interested in exactly?

**Comment by weeyum** [comment]
closing this issue since there's been no follow up, please open a new one if you're still interest
